spring:
  datasource:
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5434/transacoes}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
